# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
print(A.ndim)
print(A.shape)
print(A.size)
print(type(A))

2
(3, 5)
15
<class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [5]:
print(B - C)
print()
print(B * C)
print()
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(np.exp(B))
print()
print(B.min())
print()
print(B.min(axis=1))
print()
print(B.min(axis=0))
print()
print(np.argmin(B))
print()
print(np.argmin(B.min(axis=1)))
print()
print(np.argmin(B.min(axis=0)))
print()
print(B.sum())
print()
print(np.mean(B))
print()
print(np.median(B))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

1

[1 4 7]

[1 2 3]

0

0

0

45

5.0

5.0


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [8]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [10]:
# It is considered a complete slices.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [11]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [13]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [14]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [15]:
# np.arange(30) creates an array with 30 elements (0 to 29).
# a.reshape((2, 3, -1)) will reshape the array into two arrays with three rows each.
# If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [16]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [17]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [18]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [19]:
def add_mult_matrices(m1, m2, math):
    try:            
        if (isinstance(m1, np.ndarray) & isinstance(m2, np.ndarray)):
            if (math == "add"):
                if(m1.size == m2.size):
                    return print(m1 + m2)
                else:
                    print("Function add_mult_matrices error: Matrices is not of the same size.")
                
            elif (math == "multiply"):
                d1 = m1.shape
                r1, c1 = d1

                d2 = m2.shape
                r2, c2 = d2
                
                if(c1 == r2):
                    return print(np.dot(m1,m2))
                else:
                    print("Function add_mult_matrices error: Number of columns in the first matrix is not equal to the number of rows in the second matrix.")
                
            else:
                print("Function add_mult_matrices error: Use either add or multiply.")        
            
        else:
            print ("Function add_mult_matrices error: Requires two arguments of the type ndarray.")
    
    except ValueError:
        print ("Function add_mult_matrices error: When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform.")
                
if __name__ == "__main__":
    
    # m1 = np.array([[2,3,4],[5,4,1]])
    # m1 = np.array([[1,2],[2,1]])
    # m1 = np.array([[2,2,2],[2,2,2]])
    m1 = np.array([[1,2],[2,4]])    
    # m1 = np.ndarray(shape=(2,2))
    # m1 = 2
    
    # m2 = np.array([[2,5],[3,4],[4,1]])
    # m2 = np.array([[2,2],[2,2],[2,2]])
    # m2 = np.array([[1,0],[0,1]])
    # m2 = np.array([[2,1],[1,3]])
    m2 = np.array([[4,3],[0,2]])    
    # m2 = np.ndarray(shape=(2,2))    
    # m2 = 1
    
    # add_mult_matrices(m1, m2, "add")
    add_mult_matrices(m1, m2, "multiply")
    # add_mult_matrices(m1, m2, "substract")   

[[ 4  7]
 [ 8 14]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [20]:
# Uppgift 10.1.1
# a) En rad och två kolumner, 1 x 2.
# b) 5x = 5(4,3) = (20,15)
# c) 3x = 3(4,3) = (12,9)
# d) 5x + 3x = 5(4,3) + 3(4,3) = (20,15) + (12,9) = (32,24)
# e) 8x = 8(4,3) = (32,24)
# f) 4x - x = 4(4,3) - (4,3) = (12,9)
# g) (4,3) = (4)
#            (3)
# h) Ej definerat
# i) 5

# Uppgift 10.1.2
# a) Fyra rader och en kolumn, 4 x 1.
# b) 2v = (6)
#         (14)
#         (0)
#         (22)
# c) 5v + 2v = (15) + (6) = (21)
#              (35)   (14)  (49)
#              (0)    (0)   (0)
#              (55)   (22)  (77)
# d) 4v - 2v = (12) - (6) = (6)
#              (21)   (14)  (7)
#              (0)    (0)   (0)
#              (44)   (22)  (22)
# e) (3) = (3,7,0,11)
#    (7)
#    (0)
#    (11)
# f) 13,37

# Uppgift 10.1.3
# a) 7,14
# b) 7,14 - 3,87 = 4,27

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [21]:
# Uppgift 10.2.1
# a) (4, 2, -2)
#    (2, -2, 2)
#
# b) (0, -4, 3)
#    (0, -2, -4)
#
# c) Subtraction can only be performed on order of same matrices.
#
# d) (6, 8) - (3, 6) = (3, 2)
#    (8, 6)   (6, 3)   (2, 3)
#
# e) (4, 3) + (6, 8) = (10, 11)
#    (3, 4)   (8, 6)   (11, 10)
# 
# f) (4, 2) - (8, 6) = (-4, -4)
#    (2, 4)   (6, 8)   (-4, -4)
#
# g) Subtraction can only be performed on order of same matrices. 
#
# h) Not same amount of columns in A as rows in B.
#
# i) (1x3 + 2x4) (1x4 + 2x3) = (11, 10)
#    (2x3 + 1x4) (2x4 + 1x3)   (10, 11)
#
# j) [[  8 -10  -3]
#     [ 10  -8   0]]
#
# k) [[1 2]
#     [2 1]]
#
# i) [[5 2]
#     [7 4]]
#
# Uppgift 10.2.2
#    [[29 26]
#     [26 42]]
#
# Uppgift 10.2.3
# AB = [[ 4  7]
#       [ 8 14]]
#
# AC = [[ 4  7]
#       [ 8 14]]
#
# AB is equal to AC.
#
#
# A = [[ 2  1]
#       [ 1 3]]
#
# C = [[ 4  3]
#       [ 0 2]]
# A is not equal to C.

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [22]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [23]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [24]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [25]:
# How can you check if v1 and v2 is a view or copy?
print(v1.base is None) # v1 is a copy
print(v2.base is None) # v2 is a view
# If you change the last element in v2 to 123, will the last element in v1 be changed? Why?
print(v1)
print(v2)
# Yes. v1 (copy) share the same data buffer as v2 (view).

True
False
[  0   1   2 123]
[  2 123]
